analyzer:
  errors:
    no_default_cases: ignore
    one_member_abstracts: ignore
    sort_constructors_first: ignore
    use_setters_to_change_properties: ignore
include: package:very_good_analysis/analysis_options.yaml
