arb-dir: lib/config/l10n/arb
template-arb-file: app_en.arb
output-localization-file: app_localizations.dart
nullable-getter: false
#use-escaping: true
untranslated-messages-file: lib/config/l10n/missing_translation.txt