name: logger_manager
description: "Package for managing data/errors logs"
version: 0.0.1
publish_to: none

environment:
  sdk: ">=3.5.0 <4.0.0"
  flutter: ">=3.24.0"

dependencies:
  azure_application_insights: ^4.0.1
  collection: ^1.18.0
  encrypt: ^5.0.3
  firebase_analytics: ^11.3.3
  firebase_core: ^3.6.0
  firebase_crashlytics: ^4.1.3
  flutter:
    sdk: flutter
  http: ^1.2.0
  intl: any
  logger: ^2.4.0
  path_provider: ^2.1.4
  pointycastle: ^3.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^6.0.0

flutter:
  generate: true
